name: Build and run

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build Rx
      run: gcc -o Rx Reciever.c
    - name: build Tx
      run: gcc -o Tx Tx.c
    - name: run
      run: ./Tx
